### ISSUE TITLE
You are given a string. You need to partition that string such that each substrings after partitioning would be palindromic string. You have to do this work with minimum number of partitioning.

### ISSUE THREAD

**Issue by aastha-b** [dsc-gtbit/HacktoberFest-20-GTBIT-Competitive#9]
Try optimizing the code using dynamic programming

**Comment by Delkhaz** [comment]
Hi @aastha-b, can i work on this ?

**Comment by aditsawant** [comment]
Hey @aastha-b, I can solve this problem in C++. Please assign it to me.

**Comment by aastha-b** [comment]
@Delkhaz Yes you can and try applying dynamic programming in it
